### ISSUE TITLE
GSI2DART build/run question

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#49] opened 2020-08-18 16:51 UTC
While testing the DART software, I compile and then try to run the **gsi_to_dart** program. Apparently it is designed to require more mpi tasks than ensemble members, but the _quickbuild.csh_ and _mkmf_gsi_to_dart_ did not force an mpi build, so I am making that the default. That leads me to another observation ... the code issues the following run-time errors:

```
0[1125] cisl-minnetonka:~/<3>obs_converters/GSI2DART/work % mpirun -np 4 ./gsi_to_dart 
 running on            4  processors ...
 FATAL ERROR in find_namelist_in_file
    initialize_utilities() or initialize_mpi_utilities()
    must be called before calling find_namelist_in_file().
   utilities_mod.f90
   
   
    stopping.
 FATAL ERROR in find_namelist_in_file
    initialize_utilities() or initialize_mpi_utilities()
    must be called before calling find_namelist_in_file().
   utilities_mod.f90
   
   
    stopping.
 FATAL ERROR in find_namelist_in_file
    initialize_utilities() or initialize_mpi_utilities()
    must be called before calling find_namelist_in_file().
   utilities_mod.f90
   
   
    stopping.

 --------------------------------------
 Starting ... at YYYY MM DD HH MM SS = 
                 2020  8 18 10 41  6
 Program gsi2dart
 --------------------------------------

  set_nml_output Echo NML values to log file only
 total number of mpi tasks must be >= ens_size+1
 tasks, ens_size+1 =            4          81
 ****STOP2****  ABORTING EXECUTION w/code=          19
 ****STOP2****  ABORTING EXECUTION w/code=          19
application called MPI_Abort(MPI_COMM_WORLD, 19) - process 0
```

So - I know people are using this, but I don't see how they are using it unless they make modifications. Specifically,
```
! Print out some info
if ( nproc == 0 ) call initialize_utilities('gsi2dart')
```
Doesn't seem like the right course of action.  Any advice from the people who are using this? How?

**Comment by hkershaw-brown** [comment] 2022-05-24 20:24
Closing: I can't reproduce this problem. The current code is calling `initialize_utilities` before `find_namelist_in_file`

```
gsi2dart:
  call initialize_mpi_utilities
       -> call initialize_utilities
   ...
  call find_namelist_in_file
```

**Closed by hkershaw-brown** 2022-05-24 20:24 UTC
Labels: Bug
